### ISSUE TITLE
No support for InterfaceSupportsErrorInfo

### ISSUE THREAD

**Issue by vidarsumo** [omegahat/RDCOMClient#28]
I've been using the RDCOMClient packge in R for over a year now without a problem.

Now suddenly it's giving me an error:

```
<checkErrorInfo> 80070057 
No support for InterfaceSupportsErrorInfo
checkErrorInfo -2147024809
Error: The parameter is incorrect.
```

Here is my code (I've cleaned the code due to privacy):

```
library(RDCOMClient)
library(lubridate)

rmarkdown::render("/report.Rmd", encoding = "UTF-8")

OutApp <- COMCreate("Outlook.Application")
outMail = OutApp$CreateItem(0)

text <- paste("Attached is the report")
path_to_attachment <- "W:\\Rwd\\report\\report_this_month\\report.pdf"

outMail[["to"]] = "user@xyz.is"
outMail[["subject"]] = "Monthly report"
outMail[["htmlbody"]] = text
outMail[["attachments"]]$Add(path_to_attachment)

outMail$Send()

rm(OutApp, outMail)
```

I have few other scripts that I schedule to send emails. One of them uses the blastula package (also sends email through Outlook) and I have no problem there.

Any idea why I'm getting this error?

**Comment by refpuz** [comment]
I have also encountered this error on a few scripts myself that have worked until very recently. I have narrowed it down to the "HTMLBody" property of the outmail object causing the issue. If you use the plain-text "body" property instead, it works flawlessly. Your post is the only one online that I have found that has this issue as well.

**Comment by vidarsumo** [comment]
Awesome! This works perfectly :) Thank you so much @refpuz
