### ISSUE TITLE
rdcom.err file gets too large

### ISSUE THREAD

**Issue by Avinash007** [omegahat/RDCOMClient#34]
In C: drive, the rdcom.err file has become more than 50GB. Can I delete this file? 
Will it cause any issues for the package to run?

**Comment by duncantl** [comment]
Hi.  Yes, you can delete it and everything should work. 
In case things do fail after deleting the file, you can just create an empty file with that name in the same directory.

**Comment by Avinash007** [comment]
Thank you so much.
